.comp Graph<NodeT> {
    .type Path = [ head: NodeT, tail: Path ]

    .decl edge(from: NodeT, to: NodeT) overridable
    .decl path(from: NodeT, to: NodeT, len: number, path: Path)

    // Base case - if there is an edge 
    path(from, to, 1, [from, [to, nil]]) :-
        edge(from, to).

    path(from, to, len + 1, [from, p]) :-
        edge(from, x),
        path(x, to, len, p).

    // Pick shortest path 
    path(x, y, l1, _) <= path(x, y, l2, _) :- l1 > l2.

    .decl pathAt(from: NodeT, to: NodeT, idx: number, node: NodeT)
    pathAt(from, to, 0, from) :- path(from, to, _, _).
    pathAt(from, to, len, to) :- path(from, to, len, _).
    pathAt(from, to, i + 1, nd) :-
        path(from, to, _, [from, [x, _]]),
        x != to,
        pathAt(x, to, i, nd).
}

.comp IdGraph : Graph<id> { }