/**
 * Note: No need for this component to be a graph since the linearizedBaseContracts lists
 * all ancestors.
 */
.comp Inheritance  {
    /// Specifies that a childContractId inherits from baseContractId (or is the same contract)
    .decl inherits(childContractId: ContractDefinitionId, baseContractId: ContractDefinitionId)
    inherits(childContractId, baseContractId) :- ContractDefinition(childContractId), childContractId = baseContractId.
    inherits(childContractId, baseContractId) :-
        ContractDefinition(childContractId),
        ContractDefinition(baseContractId),
        ContractDefinition_linearizedBaseContracts(childContractId, baseContractId, _).

    .decl inheritsStrict(childContractId: ContractDefinitionId, baseContractId: ContractDefinitionId)
    inheritsStrict(childContractId, baseContractId) :- inherits(childContractId, baseContractId), childContractId != baseContractId.

    /// Specifies that a child FunctionDefinition/ModifierDefinition/VariableDeclaration overrides a
    /// base FunctionDefinition/ModifierDefinition
    /// There are 3 cases:
    ///     - function overriding a function
    ///     - public state var overriding a function
    ///     - modifier overriding a modifier
    .decl overrides(childNode: id, baseFun: id, inContract: ContractDefinitionId)

    /// Case 1: Function overriding a function
    overrides(childFun, baseFun, childContract) :-
        FunctionDefinition_scope(childFun, childContract),
        FunctionDefinition_scope(baseFun, baseContract),
        inheritsStrict(childContract, baseContract),
        FunctionDefinition_signature(childFun, sig),
        FunctionDefinition_signature(baseFun, sig).

    /// Case 2: Public state var overriding a function
    overrides(childVar, baseFun, childContract) :-
        VariableDeclaration(childVar),
        VariableDeclaration_stateVariable(childVar, 1),
        VariableDeclaration_visibility(childVar, "public"),
        parent(childContract, childVar),
        FunctionDefinition_scope(baseFun, baseContract),
        inheritsStrict(childContract, baseContract),
        VariableDeclaration_signature(childVar, sig),
        FunctionDefinition_signature(baseFun, sig).

    /// Case 3: Modifier overriding a modifier
    overrides(childMod, baseMod, childContract) :-
        ContractDefinition(baseContract),
        ContractDefinition(childContract),
        inheritsStrict(childContract, baseContract),
        ModifierDefinition(childMod),
        parent(childContract, childMod),
        ModifierDefinition(baseMod),
        parent(baseContract, baseMod),
        ModifierDefinition_name(childMod, modName),
        ModifierDefinition_name(baseMod, modName).

    // Given an argument index `argIdx` of the constructor of a base contract `base` in a contract `mdc`, find the exact
    // expression `val` thay corresponds to the value passed to that arg. Note that this may appear in an intermediate
    // base class, either in a `ModifierInvocation` or an `InhertianceSpecifier`.
    // Note that its a compiler error to specify a base's arguments more than once (even with diamond inheritance).
    // So we don't have to worry about order here.
    .decl findBaseConstructorArg(mdc: ContractDefinitionId, base: ContractDefinitionId, argIdx: number, val: ExpressionId)

    // Case 1: ModifierInvocation in some base (either mdc or an intermediate base)
    findBaseConstructorArg(mdc, base, argIdx, val) :-
        ContractDefinition_linearizedBaseContracts(mdc, someBase, _),
        FunctionDefinition_scope(constr, someBase),
        FunctionDefinition_isConstructor(constr, 1),
        FunctionDefinition_modifiers(constr, mod, _),
        ModifierInvocation_vReferencedDeclaration(mod, base),
        ContractDefinition(base),
        ModifierInvocation_arguments(mod, val, argIdx).

    // Case 2: InhertianceSpecifier in some base (either mdc or an intermediate base)
    findBaseConstructorArg(mdc, base, argIdx, val) :-
        ContractDefinition_linearizedBaseContracts(mdc, someBase, _),
        parent(someBase, inhSpec),
        InheritanceSpecifier_referesTo(inhSpec, base),
        InheritanceSpecifier_arguments(inhSpec, val, argIdx),
        ContractDefinition(base).

    .decl resolvesToHelper(def: id, resolved: id, inContract: ContractDefinitionId, idx: number)
    resolvesToHelper(def, def, inContract, i) :-
        ContractDefinition_linearizedBaseContracts(inContract, someBase, i),
        (FunctionDefinition(def) ; ModifierDefinition(def) ; isPublicStateVar(def)),
        parent(someBase, def).

    resolvesToHelper(def, resolved, inContract, i) :-
        ContractDefinition_linearizedBaseContracts(inContract, someBase, i),
        (FunctionDefinition(resolved) ; ModifierDefinition(resolved) ; isPublicStateVar(resolved)),
        overrides(resolved, def, someBase).
        
    resolvesToHelper(def, resolved, inContract, i) :-
        ContractDefinition_linearizedBaseContracts(inContract, someBase, i),
        resolvesToHelper(def, resolved, inContract, i + 1),
        !overrides(_, def, someBase).

    // Relation determining to what exact FunctionDefinition/ModifierDefinition
    // `resolved`, a given base FunctionDefintion/ModifierDefinitionId `def`
    // resolves to inside the most-derived contract `inContract`.
    .decl resolvesTo(def: id, resolved: id, inContract: ContractDefinitionId)
    resolvesTo(def, resolved, inContract) :-
        resolvesToHelper(def, resolved, inContract, 0).
}