.type CallListNode = Node { id: id }
                  | Call { id: CallsiteType, target: CalleeType }
                  | Modifier { id: FunctionDefinitionId, idx: number, placeHolder: PlaceholderStatementId }
                  | BaseConstructor { mdc: ContractDefinitionId, baseIdx: number }
.type CallList = [ head: CallListNode , tail: CallList ]
.type Context = [ mdc: ContractDefinitionId, callList: CallList]
.functor findRecursiveCall(callList: CallList, fun: id): CallList stateful
.functor concatCallLists(a: CallList, b: CallList): CallList stateful

.comp InterproceduralSuccessor : Graph<Context> {
    .decl isNodeEndOfFunOrMod(n: id)
    isNodeEndOfFunOrMod(n) :-
        Return(n) ;
        FunctionDefinition_body(_, n, 1) ;
        ModifierDefinition_body(_, n, 1).

    // Helper function to compute the call list corresponding to the first node to execute in a modifier invocation 
    // `modInv` in contract `inContract`.
    .decl modifierFirst(fun: FunctionDefinitionId, inContract: ContractDefinitionId, idx: number, firstCallList: CallList)

    // Case 1: Modifier has no args - first node in the body
    modifierFirst(fun, inContract, idx, [$Node(bodyFirst), nil]) :-
        FunctionDefinition_modifiers(fun, modInv, idx),
        !ModifierInvocation_arguments(modInv, _, _),
        ModifierInvocation_vReferencedDeclaration(modInv, modDef),
        ModifierDefinition(modDef),
        inh.resolvesTo(modDef, actualModDef, inContract),
        ModifierDefinition_body(actualModDef, body, 1),
        cfg.succ.succ_first(body, bodyFirst).

    // Case 2: Modifier has args - first arg
    modifierFirst(fun, inContract, idx, [$Node(argFirst), nil]) :-
        FunctionDefinition_modifiers(fun, modInv, idx),
        inh.resolvesTo(_, fun, inContract),
        ModifierInvocation_vReferencedDeclaration(modInv, modDef),
        ModifierDefinition(modDef),
        ModifierInvocation_arguments(modInv, firstArg, 0),
        cfg.succ.succ_first(firstArg, argFirst).

    // Helper function to compute the call list corresponding to the first node to execute in function `fun` in 
    // contract `inContract`.
    .decl funFirst(fun: FunctionDefinitionId, inContract: ContractDefinitionId, callList: CallList)

    // Case 1: fun doesnt have modifiers - just add the first thing in the body
    funFirst(fun, inContract, [$Node(bodyFirst), nil]) :-
        ContractDefinition(inContract),
        !FunctionDefinition_modifiers(fun, _, _),
        FunctionDefinition_body(fun, body, 1),
        cfg.succ.succ_first(body, bodyFirst).

    // Case 2: fun has modifiers - just add the first thing in the first modifier's body 
    funFirst(fun, inContract, newCallList) :-
        modifierFirst(fun, inContract, 0, modEntryCallList),
        newCallList = @concatCallLists(modEntryCallList, [$Modifier(fun, 0, -1), nil]).

    // Helper relation finding all public/external function definitions that may be called
    // when entering a given contract. Note this ignores constructors as they are handled separately
    .decl entrypointIn(fun: FunctionDefinitionId, inContract: ContractDefinitionId)
    entrypointIn(fun, inContract) :-
        inh.resolvesTo(_, fun, inContract), 
        // In 0.4.x visibility could be omitted ("default") which defaults to public.
        (FunctionDefinition_visibility(fun, "public"); FunctionDefinition_visibility(fun, "external") ; FunctionDefinition_visibility(fun, "default")),
        // Note we handle constructors separately
        FunctionDefinition_isConstructor(fun, 0).

    // ===================== Main edge relation ========================================

    // --------------------- Non-recursive and recursive functions ---------------------
    // We have edges from start (nil) to any public/external functions
    edge(nil, [mdc, callList]) :-
        entrypointIn(fun, mdc),
        funFirst(fun, mdc, callList).

    // Inherit all non-call edges from intraprocedural cfg. 
    // Note we allow external calls here - they are considerd orthogonal to the interprocedural CFG since
    // control flow could jump to any unknown contract.
    edge([mdc, [$Node(n1), callList]], [mdc, [$Node(n2), callList]]) :-
        edge(_, [mdc, [$Node(n1), callList]]),
        cfg.succ.edge(n1, n2),
        (!mayCallIn(n2, _, mdc) ; externalCall(n2)),
        // Ignore placeholders - they are handled separately in the modifier rules below.
        !PlaceholderStatement(n2).
        
    // For all non-recursive calls add an edge to the
    // entry of the callee with the callsite added to the callList.
    edge([mdc, [$Node(n1), callList]], [mdc, newCallList]) :-
        edge(_, [mdc, [$Node(n1), callList]]),
        cfg.succ.edge(n1, n2),
        mayCallIn(n2, fun, mdc),
        !externalCall(n2),
        @findRecursiveCall(callList, fun) = nil,
        funFirst(fun, mdc, funCallListSuffix),
        newCallList = @concatCallLists(@concatCallLists(funCallListSuffix, [$Call(n2, fun), nil]), callList).

    // For recursive calls add an edge to the entry of the callee, at the
    // earlier call list where it was invoked.
    edge([mdc, [$Node(n1), callList]], [mdc, newCallList]) :-
        edge(_, [mdc, [$Node(n1), callList]]),
        cfg.succ.edge(n1, n2),
        mayCallIn(n2, fun, mdc),
        !externalCall(n2),
        @findRecursiveCall(callList, fun) = earlierRecCallList,
        earlierRecCallList != nil,
        funFirst(fun, mdc, funCallListSuffix),
        newCallList = @concatCallLists(funCallListSuffix, earlierRecCallList).

    // For all recursive calls we remember the callList at the recursive call site as an
    // additional recursive return
    .decl additionalRecursiveReturn(fun: FunctionDefinitionId, mdc: ContractDefinitionId, callList: CallList)
    additionalRecursiveReturn(fun, mdc, [$Call(n2, fun), callList]) :-
        edge(_, [mdc, [$Node(n1), callList]]),
        cfg.succ.edge(n1, n2),
        mayCallIn(n2, fun, mdc),
        !externalCall(n2),
        @findRecursiveCall(callList, fun) != nil.

    // Normal return edge
    edge(
        [mdc, [$Node(n), [$Call(callsite, fun), rest]]],
        [mdc, [$Node(callsite), rest]]
    ) :-
        edge(_, [mdc, [$Node(n), [$Call(callsite, fun), rest]]]),
        isNodeEndOfFunOrMod(n).

    // Return to additional recursive callsites
    edge(
        [mdc, [$Node(n), [$Call(callsite, fun), rest]]],
        [mdc, [$Node(otherCallsite), otherCallList]]
    ) :-
        edge(_, [mdc, [$Node(n), [$Call(callsite, fun), rest]]]),
        isNodeEndOfFunOrMod(n),
        additionalRecursiveReturn(fun, mdc, [$Call(otherCallsite, fun), otherCallList]).

    // --------------------- Modifiers -------------------------------------
    // When encountering a place-holder if there is a ModifierInvocation enter it.
    edge(
        [mdc, [$Node(n1), [$Modifier(fun, modInvIdx, oldPlaceHolder), callList]]],
        [mdc, newCallList]
    ) :-
        edge(_, [mdc, [$Node(n1), [$Modifier(fun, modInvIdx, oldPlaceHolder), callList]]]),
        cfg.succ.edge(n1, placeHolder),
        PlaceholderStatement(placeHolder),
        modifierFirst(fun, mdc, modInvIdx + 1, nextModCallList),
        newCallList = @concatCallLists(
            nextModCallList,
            [$Modifier(fun, modInvIdx + 1, placeHolder), [$Modifier(fun, modInvIdx, oldPlaceHolder), callList]]
        ).

    // When encountering a place-holder if there is no next ModifierInvocation enter the function.
    // Note we push a dummy `$Modifier(fun, -1, placeHolder)` on the callList to remember the last placeholder.
    edge(
        [mdc, [$Node(n1), [$Modifier(fun, modInvIdx, oldPlaceHolder), callList]]],
        [mdc, [$Node(bodyFirst), [$Modifier(fun, -1, placeHolder), [$Modifier(fun, modInvIdx, oldPlaceHolder), callList]]]]
    ) :-
        edge(_, [mdc, [$Node(n1), [$Modifier(fun, modInvIdx, oldPlaceHolder), callList]]]),
        cfg.succ.edge(n1, placeHolder),
        PlaceholderStatement(placeHolder),
        !FunctionDefinition_modifiers(fun, _, modInvIdx + 1),
        FunctionDefinition_body(fun, body, 1),
        cfg.succ.succ_first(body, bodyFirst).

    // Modifier return when we return to another modifier
    edge(
        [mdc, [$Node(n), [$Modifier(fun, modInvIdx, placeHolder), rest]]],
        [mdc, [$Node(placeHolder), rest]]
    ) :-
        edge(_, [mdc, [$Node(n), [$Modifier(fun, modInvIdx, placeHolder), rest]]]),
        placeHolder >= 0,
        isNodeEndOfFunOrMod(n).

    // Modifier return when we return from the root modifier
    // Note its ok to include `$Call(callsite, target)` in the matched context, since the only
    // other case is when this is the modifier of the entrypoint into the contract. In this case there is no next edge.
    edge(
        [mdc, [$Node(n), [$Modifier(fun, modInvIdx, -1), [$Call(callsite, target), rest]]]],
        [mdc, [$Node(callsite), rest]]
    ) :-
        edge(_, [mdc, [$Node(n), [$Modifier(fun, modInvIdx, -1), [$Call(callsite, target), rest]]]]),
        isNodeEndOfFunOrMod(n).

    // --------------------- Modifiers Arugments -------------------------------------
    // When one argument is done, go to the next
    edge(
        [mdc, [$Node(n1), [$Modifier(fun, modInvIdx, placeHolder), rest]]],
        [mdc, [$Node(n2), [$Modifier(fun, modInvIdx, placeHolder), rest]]]
    ) :-
        edge(_, [mdc, [$Node(n1), [$Modifier(fun, modInvIdx, placeHolder), rest]]]),
        FunctionDefinition_modifiers(fun, modInv, modInvIdx),
        ModifierInvocation_arguments(modInv, n1, modInvIdx),
        ModifierInvocation_arguments(modInv, nextArg, modInvIdx + 1),
        cfg.succ.succ_first(nextArg, n2).

    // When last argument is done, go to the body of the modifier 
    edge(
        [mdc, [$Node(n1), [$Modifier(fun, modInvIdx, placeHolder), rest]]],
        [mdc, [$Node(bodyFirst), [$Modifier(fun, modInvIdx, placeHolder), rest]]]
    ) :-
        edge(_, [mdc, [$Node(n1), [$Modifier(fun, modInvIdx, placeHolder), rest]]]),
        FunctionDefinition_modifiers(fun, modInv, modInvIdx),
        ModifierInvocation_arguments(modInv, n1, argIdx),
        !ModifierInvocation_arguments(modInv, _, argIdx + 1),
        ModifierInvocation_vReferencedDeclaration(modInv, modDef),
        ModifierDefinition(modDef),
        inh.resolvesTo(modDef, actualModDef, inContract),
        ModifierDefinition_body(actualModDef, body, 1),
        cfg.succ.succ_first(body, bodyFirst).
}