.comp CallGraph : IdGraph {
    // Call due to an expression inside the function
    edge(caller, callee) :- 
        FunctionDefinition(caller),
        ancestor(caller, exprId),
        mayCall(exprId, callee).

    // Implicit call to base constructor
    edge(caller, callee) :- 
        FunctionDefinition_isConstructor(caller, 1),
        mayCall(caller, callee).

    // Check if a function is recursive
    .decl isRecursive(f: FunctionDefinitionId)
    isRecursive(f) :-
        FunctionDefinition(f),
        path(f, f, _).
}